nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpEnableEsmLoader: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs
